### PR TITLE
Code Overhaul (READ DESC)

### PR DESCRIPTION
**Pull request by Calculus-Master**
- Moved all the method inits to the top with their comment docs, along with axis/button initializers and defaultVel
- Moved all the methods declarations to the bottom under the main method, rearranged them so the most important / bug prone ones are near the top under the main method
- Moved manual control system out of the main method into its own separate method, preparing for a similar thing for autonomous
- Made the drive method much more efficient
- Removed the useless setDefaultVel method

### CODE REVIEW

**Comment by Sajo8** [comment]
- no. why. just no. (return the methods to where they are, it's useless predeclaring them right now - var initializations are fine tho)
- main method goes at the bottom, after all the code. move it back there
- k
- you just reduced LOC at the sake of readability, id say revert it back. the multi line is easier to read than the one-line thing (i forget what it's called)
- k

also `main()` needs to be a function of type `int`

**Comment by Sajo8** [comment]
i know it's not needed but i think you should split the if statements into multiple lines to make it easier to read

**Comment by Sajo8** [comment]
also update comments for incrVel and decrVel vars to reflect how much it actly increases it by

**Comment by Sajo8** [comment]
nice, we can test then merge

**Comment by Calculus-Master** [comment]
Did lots of work afterschool Thursday 11/21, this branch is now useless

**Pull request closed without merging**
